# Generated by Django 4.1.7 on 2024-04-30 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyComposition',
            fields=[
                ('familyComposition', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.CharField(default=0, max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('cstat', models.CharField(max_length=10)),
                ('relation_to_patient', models.CharField(max_length=10)),
                ('hea', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('mi', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UIS',
            fields=[
                ('uis', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospno', models.CharField(max_length=30)),
                ('phil_no', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('total_income', models.CharField(default=0, max_length=20)),
                ('total_expense', models.CharField(default=0, max_length=20)),
                ('category', models.CharField(default='?', max_length=10)),
                ('householdsize', models.CharField(default=0, max_length=5)),
                ('has_scsr', models.BooleanField(default=False)),
                ('has_mssat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SWA',
            fields=[
                ('swa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swa_desc', models.CharField(max_length=1500)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.uis')),
            ],
        ),
        migrations.CreateModel(
            name='SCSR',
            fields=[
                ('scsr', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer', models.CharField(max_length=150)),
                ('special_skill', models.CharField(max_length=50)),
                ('date_admission', models.CharField(max_length=30)),
                ('room', models.CharField(max_length=30)),
                ('tdd', models.CharField(max_length=50)),
                ('housing_material', models.CharField(max_length=100)),
                ('fuel_source', models.CharField(max_length=100)),
                ('problem_presented', models.CharField(max_length=300)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.uis')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('recommendation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_assistance', models.CharField(max_length=50)),
                ('amt_of_assistance', models.CharField(max_length=25)),
                ('mode_of_assistance', models.CharField(max_length=25)),
                ('fund_source', models.CharField(max_length=15)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.uis')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemPresented',
            fields=[
                ('problemPresented', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=250)),
                ('prob_desc', models.CharField(max_length=250)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.uis')),
            ],
        ),
        migrations.CreateModel(
            name='MSSAT',
            fields=[
                ('mssat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doac', models.CharField(max_length=50)),
                ('basic_ward', models.CharField(max_length=50)),
                ('non_basic', models.CharField(max_length=50)),
                ('mss_no', models.CharField(max_length=50)),
                ('tla', models.CharField(max_length=50)),
                ('src_referal_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('cnum', models.CharField(max_length=20)),
                ('employer', models.CharField(default='NONE', max_length=100)),
                ('phil_mem', models.CharField(max_length=20)),
                ('mswd_cassif', models.CharField(max_length=30)),
                ('marginalized_sec_mem', models.CharField(max_length=50)),
                ('fuel_source', models.CharField(max_length=100)),
                ('amt_fuel_source', models.CharField(default=[0, 0, 0, 0], max_length=30)),
                ('clothing_amt', models.CharField(max_length=10)),
                ('duration_of_prob', models.CharField(max_length=100)),
                ('prev_treatment', models.CharField(max_length=100)),
                ('health_accessibility_prob', models.CharField(max_length=100)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.uis')),
            ],
        ),
        migrations.CreateModel(
            name='ListofExpenses',
            fields=[
                ('listofExpenses', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('house', models.CharField(max_length=20)),
                ('amt_house', models.CharField(max_length=10)),
                ('lot', models.CharField(max_length=20)),
                ('amt_lot', models.CharField(max_length=10)),
                ('ligth_source', models.CharField(max_length=100)),
                ('amt_ligth_source', models.CharField(max_length=50)),
                ('water_source', models.CharField(max_length=100)),
                ('amt_water_source', models.CharField(max_length=50)),
                ('other_expenses', models.CharField(max_length=150)),
                ('amt_other_expenses', models.CharField(max_length=70)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.uis')),
            ],
        ),
        migrations.CreateModel(
            name='Informant',
            fields=[
                ('informant', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_intake', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('time_of_interview', models.CharField(max_length=10)),
                ('relation_to_patient', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=11)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.uis')),
            ],
        ),
        migrations.CreateModel(
            name='IdentifyingInformation',
            fields=[
                ('identifyingInformation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('pob', models.CharField(max_length=150)),
                ('permanent_address', models.CharField(max_length=150)),
                ('present_address', models.CharField(max_length=150)),
                ('cstat', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=20)),
                ('hea', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=20)),
                ('mi', models.CharField(max_length=10)),
                ('patient_type', models.CharField(max_length=10)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.uis')),
            ],
        ),
        migrations.CreateModel(
            name='Fc_other_source',
            fields=[
                ('fc_other_source', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otherSources_of_fi_desc', models.CharField(max_length=100)),
                ('otherSources_of_fi', models.CharField(max_length=15)),
                ('familyComposition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.familycomposition')),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.uis')),
            ],
        ),
        migrations.AddField(
            model_name='familycomposition',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='uis.uis'),
        ),
    ]
